# Basic
title: ShuiBo'blog
subtitle: 人生若只如初见
welcome_message: 时间在走，而你在这里。
description: 嗨，我是水波 (@saber).
creator: <a href="https://shuibo.me">@saber</a>

url: "https://shuibo.me"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: 

blog_button:
    title: 博客
    description: 访问博客

nav:
    - {title: 简历, description: 我的简历, url: 'https://onev.cat'}
    - {title: 关于, description: 了解更多关于我, url: 'http://about.onevcat.com/'}
    - {title: 订阅, description: 邮件订阅本站, url: '//objccn.io/subscribe'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: onevcat
    # duoshuo:
# Social
social:
    weibo: caishuibo
    github: sabercoding
    twitter: saber9192
    mail: sabercoding@gmail.com

# Google Analytics
ga:
    id: UA-25719337-1
    host: shuibo.me
